config/routes.rb
Atomic::Application.routes.draw do
  get "home/index"

  devise_for :users do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
    get "/register" => "devise/registrations#new"
  end

  match "/dashboard" => "dashboard#show"

  namespace :dashboard do
    resource :profile, :questions, :display_settings, :messages, :photos
    resource :links_list, :path => 'links'
  end

  match ':profile_id' => 'profiles#show', as: :profile
  root :to => 'home#index'
end

app/models/display_setting.rb
class DisplaySetting < ActiveRecord::Base
  belongs_to :profile
end

app/models/links_list.rb
class LinksList < ActiveRecord::Base
  belongs_to :profile

  SITES = %w[twitter facebook tumblr flickr yelp]
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :profile
  mount_uploader :image, ImageUploader
  validates :image, :presence => true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_many :photos, :dependent => :destroy
  accepts_nested_attributes_for :photos
  has_many :question_answers, :dependent => :destroy
  has_many :questions, :through => :question_answers
  accepts_nested_attributes_for :question_answers,
    :reject_if => proc { |attributes| attributes['body'].blank? }
  has_one :display_setting, :dependent => :destroy
  accepts_nested_attributes_for :display_setting
  has_one :links_list, :dependent => :destroy
  accepts_nested_attributes_for :links_list
  belongs_to :user
  
  validates :slug,
    :presence => true,
    :uniqueness => true,
    :length => 3..50,
    :format => { :with => /^[a-z0-9]+([-_][a-z0-9]+)*$/i }
  
  def to_param
    slug
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def first_or_email
    first_name || user.email
  end

  def main_image
    photos.first || Photo.new
  end  

  private

  def generate_slug
   slug = full_name.parameterize
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/question_answer.rb
class QuestionAnswer < ActiveRecord::Base
  belongs_to :profile
  belongs_to :question
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :profile, :dependent => :destroy
  accepts_nested_attributes_for :profile
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :profile_attributes

  before_create :create_default_profile

  private

  def create_default_profile
    p = self.profile || create_profile
    p.create_display_setting(:header_font => 'Arial', :header_font_size => 18, :body_font => 'Arial')
    p.create_links_list
    p.questions = Question.limit(3).all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user, :logged_in?  

  private
  
  # def current_user  
  #   @current_user ||= User.find(session[:user_id]) if session[:user_id]  
  # end
  
  # def logged_in?
  #   current_user != nil
  # end
  
  def require_user
    unless current_user
      store_location
      flash[:notice] = "You must be logged in to access this page"
      redirect_to login_path
      return false
    end
  end
  
  def store_location
    session[:return_to] = request.fullpath
  end
  
  def redirect_back_or_default(default, notice={})
    redirect_to(session[:return_to] || default, notice)
    session[:return_to] = nil
  end
end

app/controllers/dashboard/base_controller.rb
module Dashboard
  class BaseController < ApplicationController
    before_filter :authenticate_user!, :load_user
    layout 'dashboard'  

    private
    def load_user
      @user = current_user
      @profile = @user.profile
    end
  end
end

app/controllers/dashboard/display_settings_controller.rb
module Dashboard
  class DisplaySettingsController < BaseController
    def show
    end

    def edit
    end

    def update
      if @profile.update_attributes(params[:profile])
        redirect_to dashboard_display_settings_path, notice: 'Your profile display were successfully updated.'
      else
        render action: 'edit'
      end
    end
  end
end

app/controllers/dashboard/links_lists_controller.rb
module Dashboard
  class LinksListsController < BaseController
    def show
    end

    def edit
    end

    def update
      if @profile.update_attributes(params[:profile])
        redirect_to dashboard_links_list_path, notice: 'Your links were successfully updated.'
      else
        render action: 'edit'
      end
    end
  end
end

app/controllers/dashboard/messages_controller.rb
module Dashboard
  class MessagesController < BaseController
    def show

    end

    def edit

    end

    def update

    end
  end
end

app/controllers/dashboard/photos_controller.rb
module Dashboard
  class PhotosController < BaseController
    def show
    end

    def edit
    end

    def update
      if @profile.update_attributes(params[:profile])
        redirect_to dashboard_photos_path
      else
        render action: 'show'
      end
    end
  end
end

app/controllers/dashboard/profiles_controller.rb
module Dashboard
  class ProfilesController < BaseController
    def show
    end

    def edit
    end

    def update
      if @profile.update_attributes(params[:profile])
        redirect_to dashboard_profile_path, notice: 'Your profile was successfully updated.'
      else
        render action: 'edit'
      end
    end
  end
end

app/controllers/dashboard/questions_controller.rb
module Dashboard
  class QuestionsController < BaseController
    def show
      @questions = @profile.question_answers
    end

    def edit
      @questions = @profile.question_answers
    end

    def update
      if @profile.update_attributes(params[:profile])
        redirect_to dashboard_questions_path, notice: 'The answers to your questions have been saved'
      else
        render action: 'edit'
      end
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = current_user
    @profile = @user.profile
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @profile = Profile.find_by_slug params[:profile_id]
    if @profile
      respond_to do |format|
        format.html
        format.css
      end
    else
      redirect_to root_path, notice: "The profile for #{params[:profile_id]} could not be found."
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/dashboard/display_settings/edit.html.erb
<h2>Edit Your Profile</h2>
<%= form_for @profile, :url => dashboard_display_settings_path do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% @profile.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.fields_for :display_setting do |setting_field| %>
    <div class="field">
      <%= setting_field.label :header_font %><br />
      <%= setting_field.text_field :header_font %>
    </div>
    <div class="field">
      <%= setting_field.label :header_font_size %><br />
      <%= setting_field.text_field :header_font_size %>
    </div>
    <div class="field">
      <%= setting_field.label :body_font %><br />
      <%= setting_field.text_field :body_font %>
    </div>
  <% end %>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/dashboard/display_settings/show.html.erb
<h2>Your Profile Display Settings <small><%= link_to 'edit', edit_dashboard_display_settings_path %></small></h2>

<p>
  <b>Header Font:</b>
  <%= @profile.display_setting.header_font %>
</p>

<p>
  <b>Header Font Size:</b>
  <%= @profile.display_setting.header_font_size %>
</p>

<p>
  <b>Body Font:</b>
  <%= @profile.display_setting.body_font %>
</p>

app/views/dashboard/links_lists/edit.html.erb
<h2>Edit Your Links</h2>
<%= form_for @profile, :url => dashboard_links_list_path do |f| %>
  <%= f.fields_for :links_list do |link_field| %>
    <div class="field">
      <%= link_field.label :twitter_url, 'Twitter' %>
      <%= link_field.text_field :twitter_url %>
    </div>
    <div class="field">
      <%= link_field.label :facebook_url, 'Facebok' %>
      <%= link_field.text_field :facebook_url %>
    </div>
    <div class="field">
      <%= link_field.label :tumblr_url, 'Tumblr' %>
      <%= link_field.text_field :tumblr_url %>
    </div>
    <div class="field">
      <%= link_field.label :flickr_url, 'Flickr' %>
      <%= link_field.text_field :flickr_url  %>
    </div>
    <div class="field">
      <%= link_field.label :yelp_url, 'Yelp' %>
      <%= link_field.text_field :yelp_url %>
    </div>
  <% end %>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/dashboard/links_lists/show.html.erb
<h2>Your Links <small><%= link_to 'edit', edit_dashboard_links_list_path %></small></h2>
<% LinksList::SITES.each do |site| %>
  <p>
  <strong><%= site.titleize %>:</strong>
  <%= @profile.links_list.send("#{site}_url") %>
  </p>
<% end %>

app/views/dashboard/messages/show.html.erb
<h2>Your Messages <small>edit</small></h2>

app/views/dashboard/photos/_form.html.erb
<%= form_for [:dashboard, @profile], :url => dashboard_photos_path, :html => {:multipart => true} do |f| %>
  <%= render "shared/error_messages", :target => @profile %>
  <%= f.fields_for :photos, Photo.new do |photo_field| %>
    <%= photo_field.file_field :image %>
    <%= photo_field.hidden_field :image_cache %><br />
  <% end %>
  <%= f.submit %>
<% end %>

app/views/dashboard/photos/_photo.html.erb
<div class="photo_thumb">
  <%= image_tag photo.image_url(:thumb) %>
</div>

app/views/dashboard/photos/edit.html.erb
<h1>Photos#edit</h1>
<p>Find me in app/views/photos/edit.html.erb</p>

app/views/dashboard/photos/show.html.erb
<div class="colright">
  <p>
    We have the capacity to, as a great nation, secure the border. If East Germany could, we could. So that's what we want is a secure and sovereign nation and, you know, I don't know that all of you are Latino. Some of you look a little more Asian to me. These prisons are beautiful properties with basketball courts, bathroom facilities, toilet facilities. Many young people would love to get the hell out of cities.
  </p>
  <%= render partial: 'form' %>
</div>
<div>
  <%= render partial: @profile.photos %>
</div>

app/views/dashboard/profiles/edit.html.erb
<h2>Edit Your Profile</h2>
<%= form_for [:dashboard, @profile] do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br />
    <%= f.text_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br />
    <%= f.date_select :birthday, :start_year => 1910 %>
  </div>
  <div class="field">
    <%= f.label :ethnicity %><br />
    <%= f.text_field :ethnicity %>
  </div>
  <div class="field">
    <%= f.label :education %><br />
    <%= f.text_field :education %>
  </div>
  <div class="field">
    <%= f.label :job %><br />
    <%= f.text_field :job %>
  </div>
  <div class="field">
    <%= f.label :height %><br />
    <%= f.text_field :height %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dashboard/profiles/show.html.erb
<h2>Your Profile <small><%= link_to 'edit', edit_dashboard_profile_path %></small></h2>

<p>
<b>URL:</b>
<%= link_to "http:www.socialftw.com/#{@profile.slug}", profile_path(@profile) %>
</p>

<p>
<b>Email:</b>
<%= @user.email %>
</p>

<p>
<b>Zip Code:</b>
<%= @profile.zipcode %>
</p>

<p>
<b>Height:</b>
<%= @profile.height %>
</p>

<p>
<b>Birthday:</b>
<%= @profile.birthday %>
</p>

<p>
<b>Ethnicity:</b>
<%= @profile.ethnicity %>
</p>

<p>
<b>Education:</b>
<%= @profile.education %>
</p>

<p>
<b>Job:</b>
<%= @profile.job %>
</p>

app/views/dashboard/questions/_question.html.erb
<h3><%= question.question.body %></h3>
<p><%= question.body %></p>

app/views/dashboard/questions/edit.html.erb
<h2>Edit Your Answers</h2>
<%= form_for @profile, :url => dashboard_questions_path do |f| %>
  <%= f.fields_for :question_answers do |qa_fields| %>
    <p><strong><%= qa_fields.object.question.body %></strong></p>
    <%= qa_fields.text_area :body %>
  <% end %>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/dashboard/questions/show.html.erb
<h2>Your Questions <small><%= link_to 'edit', edit_dashboard_questions_path %></small></h2>
<%= render :partial => 'question', :collection => @profile.question_answers %>

app/views/dashboard/show.html.erb
<h1>Dashboard#show</h1>
<p>Find me in app/views/dashboard/show.html.erb</p>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br />
    <%= f.text_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br />
    <%= f.date_select :birthday %>
  </div>
  <div class="field">
    <%= f.label :ethnicity %><br />
    <%= f.text_field :ethnicity %>
  </div>
  <div class="field">
    <%= f.label :education %><br />
    <%= f.text_field :education %>
  </div>
  <div class="field">
    <%= f.label :job %><br />
    <%= f.text_field :job %>
  </div>
  <div class="field">
    <%= f.label :height %><br />
    <%= f.text_field :height %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Zipcode</th>
    <th>Birthday</th>
    <th>Ethnicity</th>
    <th>Education</th>
    <th>Job</th>
    <th>Height</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @profiles.each do |profile| %>
  <tr>
    <td><%= profile.first_name %></td>
    <td><%= profile.last_name %></td>
    <td><%= profile.zipcode %></td>
    <td><%= profile.birthday %></td>
    <td><%= profile.ethnicity %></td>
    <td><%= profile.education %></td>
    <td><%= profile.job %></td>
    <td><%= profile.height %></td>
    <td><%= link_to 'Show', profile %></td>
    <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
    <td><%= link_to 'Destroy', profile, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.css.erb
.background-container.centered {
  background-image: url(<%= asset_path @profile.main_image.image_url %>);
}

/*** Profile Box ***/
#profile_box {
  font-family: <%= @profile.display_setting.body_font %>, Tahoma, Helvetica, Verdana, sans-serif;
  top: 147px;
  background: rgba(0, 0, 0, 0.496094);
  margin-left: -480px;
  background-position: initial initial;
  background-repeat: initial initial;
  width: 403px;
}
#profile_box h1.name {
  font-family: <%= @profile.display_setting.header_font %>, Tahoma, Helvetica, Verdana, sans-serif;
  font-size: <%= @profile.display_setting.header_font_size %>px;
  color: white;
}

app/views/profiles/show.html.erb
<div class="profile" id="profile_box">
  <h1 class="name"><%= @profile.full_name %></h1>
  <ul>
    <li><b>Location</b> <%= @profile.zipcode %></li>
    <li><b>Height</b> <%= @profile.height %></li>
    <li><b>Age</b> <%= @profile.birthday %></li>
    <li><b>Ethnicity</b> <%= @profile.ethnicity %></li>
    <li><b>Education</b> <%= @profile.education %></li>
    <li><b>Job</b> <%= @profile.job %></li>
  </ul>
  <div id="profile_qa">
    <%= render :partial => 'dashboard/questions/question', :collection => @profile.question_answers %>
  </div>
  <div id="profile_links">
    <%= render :partial => @profile.links %>
  </div>
</div>